replicaCount: 1
restartPolicy: Never
# Evaluated by the post-install hook
sleepyTime: "10"
index: >-  
    <h1>Hello</h1>
    <p>This is a test</p>
image:
    repository: nginx
    tag: 1.11.0
    pullPolicy: IfNotPresent
service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 8888
    nodePort: ""
podAnnotations: {}
resources: {}
nodeSelector: {}